package model;
// Generated 25-Jan-2019 12:20:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private String name;
     private String imageUrl;
     private Set products = new HashSet(0);

    public Category() {
    }

	
    public Category(String name, String imageUrl) {
        this.name = name;
        this.imageUrl = imageUrl;
    }
    public Category(String name, String imageUrl, Set products) {
       this.name = name;
       this.imageUrl = imageUrl;
       this.products = products;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


