package model;
// Generated 26-Jan-2019 16:09:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CustomerOrder generated by hbm2java
 */
public class CustomerOrder  implements java.io.Serializable {


     private Integer id;
     private Customer customer;
     private String status;
     private Set orderedProducts = new HashSet(0);

    public CustomerOrder() {
    }

	
    public CustomerOrder(Customer customer, String status) {
        this.customer = customer;
        this.status = status;
    }
    public CustomerOrder(Customer customer, String status, Set orderedProducts) {
       this.customer = customer;
       this.status = status;
       this.orderedProducts = orderedProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set getOrderedProducts() {
        return this.orderedProducts;
    }
    
    public void setOrderedProducts(Set orderedProducts) {
        this.orderedProducts = orderedProducts;
    }




}


