package model;
// Generated 26-Jan-2019 16:09:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String email;
     private String userName;
     private String password;
     private Set customerOrders = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String email, String userName, String password) {
        this.email = email;
        this.userName = userName;
        this.password = password;
    }
    public Customer(String email, String userName, String password, Set customerOrders) {
       this.email = email;
       this.userName = userName;
       this.password = password;
       this.customerOrders = customerOrders;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getCustomerOrders() {
        return this.customerOrders;
    }
    
    public void setCustomerOrders(Set customerOrders) {
        this.customerOrders = customerOrders;
    }




}


