package model;
// Generated 26-Jan-2019 16:09:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private String name;
     private String description;
     private String imageUrl;
     private int price;
     private Set orderedProducts = new HashSet(0);

    public Product() {
    }

	
    public Product(Category category, String name, String description, String imageUrl, int price) {
        this.category = category;
        this.name = name;
        this.description = description;
        this.imageUrl = imageUrl;
        this.price = price;
    }
    public Product(Category category, String name, String description, String imageUrl, int price, Set orderedProducts) {
       this.category = category;
       this.name = name;
       this.description = description;
       this.imageUrl = imageUrl;
       this.price = price;
       this.orderedProducts = orderedProducts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public Set getOrderedProducts() {
        return this.orderedProducts;
    }
    
    public void setOrderedProducts(Set orderedProducts) {
        this.orderedProducts = orderedProducts;
    }




}


